rutos 7.02.7

diff --git a/package/base-files/files/lib/preinit/80_mount_root b/package/base-files/files/lib/preinit/80_mount_root
--- a/package/base-files/files/lib/preinit/80_mount_root
+++ b/package/base-files/files/lib/preinit/80_mount_root
@@ -1,14 +1,17 @@
-#!/bin/sh
 # Copyright (C) 2006 OpenWrt.org
 # Copyright (C) 2010 Vertical Communications
 
-restore_config() {
-	cd /
-	mv "$1" /tmp
-	tar xzf /tmp/"$1"
-	echo "etc/config/fstab" > /tmp/tmpfilename
-	tar x -O -z -f /tmp/"$1" -T /tmp/tmpfilename > /tmp/tmpfile
-	cp /rom/etc/config/hwinfo /etc/config
+missing_lines() {
+	local file1 file2 line
+	file1="$1"
+	file2="$2"
+	oIFS="$IFS"
+	IFS=":"
+	while read line; do
+		set -- $line
+		grep -q "^$1:" "$file2" || echo "$line"
+	done < "$file1"
+	IFS="$oIFS"
 }
 
 do_mount_root() {
@@ -16,23 +19,25 @@ do_mount_root() {
 	boot_run_hook preinit_mount_root
 	if [ -f /user_defaults.tgz ]; then
 		echo "- restoring user config -"
-		restore_config "user_defaults.tgz"
-		mkdir /etc/default-config
-		mv /tmp/user_defaults.tgz /etc/default-config/config.tar.gz
-		rm -f /tmp/user_defaults.tgz
+		tar -C / -xzf /user_defaults.tgz
+		mkdir -p /etc/default-config
+		mv /user_defaults.tgz /etc/default-config/config.tar.gz
+		# Prevent configuration corruption on a power loss
 		sync
+		sme.sh --preboot || echo "- sme.sh failed with code $? -"
+
 	elif [ -f /sysupgrade.tgz ]; then
 		echo "- config restore -"
-		restore_config "sysupgrade.tgz"
-		rm -f /tmp/sysupgrade.tgz
+		cp /etc/passwd /etc/group /etc/shadow /tmp
+		tar -C / -xzf /sysupgrade.tgz
+		rm -f /sysupgrade.tgz
+		missing_lines /tmp/passwd /etc/passwd >> /etc/passwd
+		missing_lines /tmp/group /etc/group >> /etc/group
+		missing_lines /tmp/shadow /etc/shadow >> /etc/shadow
+		rm /tmp/passwd /tmp/group /tmp/shadow
+		# Prevent configuration corruption on a power loss
 		sync
-	fi
-
-	if [ -f /tmp/tmpfile ] && grep -q "/overlay" /tmp/tmpfile
-	then
-		# reboot after everything else is done (in /etc/init.d/done)
-		touch /tmp/memoryexpansion
-		sync
+		sme.sh --preboot || echo "- sme.sh failed with code $? -"
 	fi
 }
 
diff --git a/package/network/services/dropbear/files/dropbear.init b/package/network/services/dropbear/files/dropbear.init
--- a/package/network/services/dropbear/files/dropbear.init
+++ b/package/network/services/dropbear/files/dropbear.init
@@ -2,39 +2,119 @@
 # Copyright (C) 2006-2010 OpenWrt.org
 # Copyright (C) 2006 Carlos Sobrinho
 
-START=50
+START=19
 STOP=50
 
 USE_PROCD=1
 PROG=/usr/sbin/dropbear
 NAME=dropbear
 PIDCOUNT=0
-EXTRA_COMMANDS="killclients"
-EXTRA_HELP="	killclients Kill ${NAME} processes except servers and yourself"
+
+extra_command "killclients" "Kill ${NAME} processes except servers and yourself"
+
+_dropbearkey()
+{
+	/usr/bin/dropbearkey "$@" 0<&- 1>&- 2>&-
+}
+
+# $1 - host key file name
+hk_verify()
+{
+	[ -f "$1" ] || return 1
+	[ -s "$1" ] || return 2
+	_dropbearkey -y -f "$1" || return 3
+	return 0
+}
+
+# $1 - hk_verify() return code
+hk_errmsg()
+{
+	case "$1" in
+	0) ;;
+	1) echo "file does not exist" ;;
+	2) echo "file has zero length" ;;
+	3) echo "file is not valid host key or not supported" ;;
+	*) echo "unknown error" ;;
+	esac
+}
+
+# $1 - config option
+# $2 - host key file name
+hk_config()
+{
+	local x m
+	hk_verify "$2"; x=$?
+	case "$x" in
+	0)	procd_append_param command -r "$2"
+		;;
+	*)	m=$(hk_errmsg "$x")
+		logger -t "${NAME}" -p daemon.warn \
+		  "option '$1', value '$2': $m, skipping"
+		;;
+	esac
+}
+
+# $1 - host key file name
+hk_config__keyfile()
+{
+	hk_config 'keyfile' "$1"
+}
+
+hk_generate_as_needed()
+{
+	local kdir kgen ktype tdir kcount tfile
+	kdir='/etc/dropbear'
+
+	kgen=''
+	for ktype in ed25519 ecdsa rsa; do
+		hk_verify "${kdir}/dropbear_${ktype}_host_key" && continue
+
+		kgen="${kgen} ${ktype}"
+	done
+
+	[ -z "${kgen}" ] && return
+
+	tdir=$(mktemp -d); chmod 0700 "${tdir}"
+
+	kcount=0
+	for ktype in ${kgen}; do
+		tfile="${tdir}/dropbear_${ktype}_host_key"
+
+		if ! _dropbearkey -t ${ktype} -f "${tfile}"; then
+			# unsupported key type
+			rm -f "${tfile}"
+			continue
+		fi
+
+		kcount=$((kcount+1))
+	done
+
+	if [ ${kcount} -ne 0 ]; then
+		mkdir -p "${kdir}"; chmod 0700 "${kdir}"; chown root "${kdir}"
+		mv -f "${tdir}/"* "${kdir}/"
+	fi
+
+	rm -rf "${tdir}"
+}
 
 append_ports()
 {
-	local ifname="$1"
+	local ipaddrs="$1"
 	local port="$2"
 
-	grep -qs "^ *$ifname:" /proc/net/dev || {
+	[ -z "$ipaddrs" ] && {
 		procd_append_param command -p "$port"
 		return
 	}
 
-	for addr in $(
-		ifconfig "$ifname" | sed -ne '
-			/addr: *fe[89ab][0-9a-f]:/d
-			s/.* addr: *\([0-9a-f:\.]*\).*/\1/p
-		'
-	); do
+	for addr in $ipaddrs; do
 		procd_append_param command -p "$addr:$port"
 	done
 }
 
 validate_section_dropbear()
 {
-	uci_validate_section dropbear dropbear "${1}" \
+	uci_load_validate dropbear dropbear "$1" "$2" \
 		'PasswordAuth:bool:1' \
 		'enable:bool:1' \
 		'Interface:string' \
@@ -42,22 +122,33 @@ validate_section_dropbear()
 		'RootPasswordAuth:bool:1' \
 		'RootLogin:bool:1' \
 		'rsakeyfile:file' \
+		'keyfile:list(file)' \
 		'BannerFile:file' \
-		'Port:list(port):22' \
+		'Port:port:22' \
 		'SSHKeepAlive:uinteger:300' \
-		'IdleTimeout:uinteger:0'
-	return $?
+		'IdleTimeout:uinteger:0' \
+		'MaxAuthTries:uinteger:3' \
+		'RecvWindowSize:uinteger:0' \
+		'mdns:bool:1' \
+		'pam:bool:0'
 }
 
 dropbear_instance()
 {
-	local PasswordAuth enable Interface GatewayPorts \
-		RootPasswordAuth RootLogin rsakeyfile \
-		BannerFile Port
+	local ipaddrs
 
-	validate_section_dropbear "${1}" || {
+	[ "$2" = 0 ] || {
 		echo "validation failed"
 		return 1
+	}
+
+	[ -n "${Interface}" ] && {
+		[ -n "${BOOT}" ] && return 0
+
+		network_get_ipaddrs_all ipaddrs "${Interface}" || {
+			echo "interface ${Interface} has no physdev or physdev has no suitable ip"
+			return 1
+		}
 	}
 
 	[ "${enable}" = "0" ] && return 1
@@ -70,53 +161,72 @@ dropbear_instance()
 	[ "${GatewayPorts}" -eq 1 ] && procd_append_param command -a
 	[ "${RootPasswordAuth}" -eq 0 ] && procd_append_param command -g
 	[ "${RootLogin}" -eq 0 ] && procd_append_param command -w
-	[ -n "${rsakeyfile}" ] && procd_append_param command -r "${rsakeyfile}"
+	if [ -n "${rsakeyfile}" ]; then
+		logger -t ${NAME} -p daemon.warn \
+			"option 'rsakeyfile' is considered to be deprecated and" \
+			"will be removed in future releases, use 'keyfile' instead"
+		hk_config 'rsakeyfile' "${rsakeyfile}"
+	fi
+	config_list_foreach "$1" "keyfile" hk_config__keyfile
 	[ -n "${BannerFile}" ] && procd_append_param command -b "${BannerFile}"
-	[ -n "${Interface}" ] && network_get_device Interface "${Interface}"
-	append_ports "${Interface}" "${Port}"
+	append_ports "${ipaddrs}" "${Port}"
 	[ "${IdleTimeout}" -ne 0 ] && procd_append_param command -I "${IdleTimeout}"
 	[ "${SSHKeepAlive}" -ne 0 ] && procd_append_param command -K "${SSHKeepAlive}"
+	[ "${MaxAuthTries}" -ne 0 ] && procd_append_param command -T "${MaxAuthTries}"
+	[ "${RecvWindowSize}" -gt 0 -a "${RecvWindowSize}" -le 1048576 ] && \
+		procd_append_param command -W "${RecvWindowSize}"
+	[ "${mdns}" -ne 0 ] && procd_add_mdns "ssh" "tcp" "$Port" "daemon=dropbear"
+	[ "${pam}" -eq 1 ] && procd_append_param command -M
+	procd_set_param respawn
 	procd_close_instance
 }
 
-keygen()
+load_interfaces()
 {
-	for keytype in rsa; do
-		# check for keys
-		key=dropbear/dropbear_${keytype}_host_key
-		[ -f /tmp/$key -o -s /etc/$key ] || {
-			# generate missing keys
-			mkdir -p /tmp/dropbear
-			[ -x /usr/bin/dropbearkey ] && {
-				/usr/bin/dropbearkey -t $keytype -f /tmp/$key 2>&- >&- && exec /etc/rc.common "$initscript" start
-			} &
-		exit 0
-		}
-	done
+	config_get interface "$1" Interface
+	config_get enable "$1" enable 1
 
-	lock /tmp/.switch2jffs
-	mkdir -p /etc/dropbear
-	mv /tmp/dropbear/dropbear_* /etc/dropbear/
-	lock -u /tmp/.switch2jffs
-	chown root /etc/dropbear
-	chmod 0700 /etc/dropbear
+	[ "${enable}" = "1" ] && interfaces=" ${interface} ${interfaces}"
+}
+
+boot()
+{
+	BOOT=1
+	start "$@"
 }
 
 start_service()
 {
-	[ -s /etc/dropbear/dropbear_rsa_host_key ] || keygen
+	hk_generate_as_needed
 
 	. /lib/functions.sh
 	. /lib/functions/network.sh
 
 	config_load "${NAME}"
-	config_foreach dropbear_instance dropbear
+	config_foreach validate_section_dropbear dropbear dropbear_instance
 }
 
 service_triggers()
 {
-	procd_add_reload_trigger "dropbear"
+	local interfaces
+
+	procd_add_config_trigger "config.change" "dropbear" /etc/init.d/dropbear reload
+
+	config_load "${NAME}"
+	config_foreach load_interfaces dropbear
+
+	[ -n "${interfaces}" ] && {
+		for n in $interfaces ; do
+			procd_add_interface_trigger "interface.*" $n /etc/init.d/dropbear reload
+		done
+	}
+
 	procd_add_validation validate_section_dropbear
+}
+
+shutdown() {
+	# close all open connections
+	killall dropbear
 }
 
 killclients()
@@ -130,7 +240,7 @@ killclients()
 	while [ "${pid}" -ne 0 ]
 	 do
 		# get parent process id
-		pid=`cut -d ' ' -f 4 "/proc/${pid}/stat"`
+		pid=$(cut -d ' ' -f 4 "/proc/${pid}/stat")
 		[ "${pid}" -eq 0 ] && break
 
 		# check if client connection
@@ -141,14 +251,14 @@ killclients()
 	done
 
 	# get all server pids that should be ignored
-	for server in `cat /var/run/${NAME}.*.pid`
+	for server in $(cat /var/run/${NAME}.*.pid)
 	 do
 		append ignore "${server}"
 	done
 
 	# get all running pids and kill client connections
 	local skip
-	for pid in `pidof "${NAME}"`
+	for pid in $(pidof "${NAME}")
 	 do
 		# check if correct program, otherwise process next pid
 		grep -F -q -e "${PROG}" "/proc/${pid}/cmdline" || {
@@ -159,7 +269,7 @@ killclients()
 		skip=0
 		for server in ${ignore}
 		 do
-			if [ "${pid}" == "${server}" ]
+			if [ "${pid}" = "${server}" ]
 			 then
 				skip=1
 				break
diff --git a/package/network/services/samba36/files/samba.init b/package/network/services/samba36/files/samba.init
--- a/package/network/services/samba36/files/samba.init
+++ b/package/network/services/samba36/files/samba.init
@@ -2,35 +2,30 @@
 # Copyright (C) 2008-2012 OpenWrt.org
 
 START=60
+USE_PROCD=1
 
 smb_header() {
-	local interface
-	config_get interface $1 interface "loopback lan"
+	config_get samba_iface $1 interface "loopback lan"
 
 	# resolve interfaces
 	local interfaces=$(
 		. /lib/functions/network.sh
 
 		local net
-		for net in $interface; do
+		for net in $samba_iface; do
 			local device
-			network_get_device device "$net" && {
-				local subnet
-				network_get_subnet  subnet "$net" && echo -n "$subnet "
-				network_get_subnet6 subnet "$net" && echo -n "$subnet "
-			}
-
+			network_is_up $net || continue
+			network_get_device device "$net"
 			echo -n "${device:-$net} "
 		done
 	)
 
 	local name workgroup description charset
-	local hostname="$(uci_get system.system.hostname)"
-    local host=$(echo "$hostname" | sed 's/[^[:print:]]//g')
+	local hostname="$(uci_get system.@system[0].hostname)"
 
-	config_get name        $1 name        "${host:-OpenWrt}"
-	config_get workgroup   $1 workgroup   "${host:-OpenWrt}"
-	config_get description $1 description "Samba on ${host:-OpenWrt}"
+	config_get name        $1 name        "${hostname:-OpenWrt}"
+	config_get workgroup   $1 workgroup   "${hostname:-OpenWrt}"
+	config_get description $1 description "Samba on ${hostname:-OpenWrt}"
 	config_get charset     $1 charset     "UTF-8"
 
 	mkdir -p /var/etc
@@ -66,6 +61,7 @@ smb_add_share() {
 	local create_mask
 	local dir_mask
 	local browseable
+	local invalid_users
 
 	config_get name $1 name
 	config_get path $1 path
@@ -75,6 +71,7 @@ smb_add_share() {
 	config_get create_mask $1 create_mask
 	config_get dir_mask $1 dir_mask
 	config_get browseable $1 browseable
+	config_get invalid_users $1 invalid_users
 
 	[ -z "$name" -o -z "$path" ] && return
 
@@ -85,24 +82,44 @@ smb_add_share() {
 	[ -n "$create_mask" ] && echo -e "\tcreate mask = $create_mask" >> /var/etc/smb.conf
 	[ -n "$dir_mask" ] && echo -e "\tdirectory mask = $dir_mask" >> /var/etc/smb.conf
 	[ -n "$browseable" ] && echo -e "\tbrowseable = $browseable" >> /var/etc/smb.conf
+	[ -n "$invalid_users" ] && echo -e "\tinvalid users = $invalid_users" >> /var/etc/smb.conf
 }
 
-start() {
+init_config() {
 	config_load samba
-	enable=`uci get -q samba.@samba[0].enable`
-	if [ "$enable" == "1" ]; then
-		config_foreach smb_header samba
-		config_foreach smb_add_share sambashare
-		service_start /usr/sbin/smbd -D
-		service_start /usr/sbin/nmbd -D
-	fi
+	CONFIG_APPEND=1 UCI_CONFIG_DIR=/var/run/config config_load samba
+
+	config_foreach smb_header samba
+	config_foreach smb_add_share sambashare
 }
 
-stop() {
-	service_stop /usr/sbin/smbd
-	service_stop /usr/sbin/nmbd
+service_triggers() {
+	procd_add_reload_trigger samba
+
+	local i
+	for i in $samba_iface; do
+		procd_add_reload_interface_trigger $i
+	done
 }
 
-reload_service() {
-	restart
+start_service() {
+	local enabled
+
+	enabled=$(uci -q get samba.@samba[0].enabled)
+	[[ "$enabled" = "1" ]] || return
+
+	init_config
+
+	procd_open_instance
+	procd_add_mdns "smb" "tcp" "445"
+	procd_set_param command /usr/sbin/smbd -F
+	procd_set_param respawn
+	procd_set_param file /var/etc/smb.conf
+	procd_close_instance
+
+	procd_open_instance
+	procd_set_param command /usr/sbin/nmbd -F
+	procd_set_param respawn
+	procd_set_param file /var/etc/smb.conf
+	procd_close_instance
 }
diff --git a/package/network/services/uhttpd/files/uhttpd.init b/package/network/services/uhttpd/files/uhttpd.init
--- a/package/network/services/uhttpd/files/uhttpd.init
+++ b/package/network/services/uhttpd/files/uhttpd.init
@@ -6,6 +6,7 @@ START=50
 USE_PROCD=1
 
 UHTTPD_BIN="/usr/sbin/uhttpd"
+PX5G_BIN="/usr/sbin/px5g"
 OPENSSL_BIN="/usr/bin/openssl"
 
 append_arg() {
@@ -42,14 +43,19 @@ generate_keys() {
 	config_get state      "$cfg" state
 	config_get location   "$cfg" location
 	config_get commonname "$cfg" commonname
+	config_get key_type   "$cfg" key_type
+	config_get ec_curve   "$cfg" ec_curve
 
 	# Prefer px5g for certificate generation (existence evaluated last)
 	local GENKEY_CMD=""
+	local KEY_OPTS="rsa:${bits:-2048}"
 	local UNIQUEID=$(dd if=/dev/urandom bs=1 count=4 | hexdump -e '1/1 "%02x"')
+	[ "$key_type" = "ec" ] && KEY_OPTS="ec -pkeyopt ec_paramgen_curve:${ec_curve:-P-256}"
 	[ -x "$OPENSSL_BIN" ] && GENKEY_CMD="$OPENSSL_BIN req -x509 -sha256 -outform der -nodes"
+	[ -x "$PX5G_BIN" ] && GENKEY_CMD="$PX5G_BIN selfsigned -der"
 	[ -n "$GENKEY_CMD" ] && {
 		$GENKEY_CMD \
-			-days ${days:-730} -newkey rsa:${bits:-2048} -keyout "${UHTTPD_KEY}.new" -out "${UHTTPD_CERT}.new" \
+			-days ${days:-730} -newkey ${KEY_OPTS} -keyout "${UHTTPD_KEY}.new" -out "${UHTTPD_CERT}.new" \
 			-subj /C="${country:-ZZ}"/ST="${state:-Somewhere}"/L="${location:-Unknown}"/O="${commonname:-OpenWrt}$UNIQUEID"/CN="${commonname:-OpenWrt}"
 		sync
 		mv "${UHTTPD_KEY}.new" "${UHTTPD_KEY}"
@@ -72,24 +78,33 @@ create_httpauth() {
 	haveauth=1
 }
 
+append_lua_prefix() {
+	local v="$1"
+	local prefix="${v%%=*}"
+	local handler="${v#*=}"
+
+	if [ "$prefix" != "$handler" ] && [ -n "$prefix" ] && [ -f "$handler" ]; then
+		procd_append_param command -l "$prefix" -L "$handler"
+	else
+		echo "Skipping invalid Lua prefix \"$v\"" >&2
+	fi
+}
+
 start_instance()
 {
 	UHTTPD_CERT=""
 	UHTTPD_KEY=""
 
 	local cfg="$1"
-	local tmp="$(uci_get system.system.hostname)"
-	local realm=$(echo "$tmp" | sed 's/[^[:print:]]//g')
+	local realm="$(uci_get system.@system[0].hostname)"
 	local listen http https interpreter indexes path handler httpdconf haveauth enb_http enb_https
 
 	config_get disabled "$cfg" disabled "0"
-	if [ "$disabled" = "1" ]; then
-		return
-	fi
+	[ "$disabled" = "1" ] && return
 
 	procd_open_instance
 	procd_set_param respawn
-	#procd_set_param stderr 1
+	procd_set_param stderr 1
 	procd_set_param command "$UHTTPD_BIN" -f
 
 	config_get config "$cfg" config
@@ -109,10 +124,16 @@ start_instance()
 	append_arg "$cfg" config "-c"
 	append_arg "$cfg" cgi_prefix "-x"
 	[ -f /usr/lib/uhttpd_lua.so ] && {
-		config_get handler "$cfg" lua_handler
-		[ -f "$handler" ] && append_arg "$cfg" lua_prefix "-l" && {
-			procd_append_param command "-L" "$handler"
-		}
+		local len
+		config_get len "$cfg" lua_prefix_LENGTH
+
+		if [ -n "$len" ]; then
+			config_list_foreach "$cfg" lua_prefix append_lua_prefix
+		else
+			config_get prefix "$cfg" lua_prefix
+			config_get handler "$cfg" lua_handler
+			append_lua_prefix "$prefix=$handler"
+		fi
 	}
 	[ -f /usr/lib/uhttpd_ubus.so ] && {
 		append_arg "$cfg" ubus_prefix "-u"
@@ -131,15 +152,14 @@ start_instance()
 	append_bool "$cfg" no_symlinks "-S" 0
 	append_bool "$cfg" no_dirlists "-D" 0
 	append_bool "$cfg" rfc1918_filter "-R" 0
-	config_get enb_http "$cfg" enablehttp 1
-	config_get enb_https "$cfg" enablehttps 1
 
 	config_get alias_list "$cfg" alias
 	for alias in $alias_list; do
 		 procd_append_param command -y "$alias"
 	done
 
-	[ "$enb_http" == "1" ] && {
+	config_get enb_http "$cfg" enable_http "1"
+	[ "${enb_http}" == "1" ] && {
 		config_get http "$cfg" listen_http
 		for listen in $http; do
 			procd_append_param command -p "$listen"
@@ -156,11 +176,12 @@ start_instance()
 		procd_append_param command -I "$path"
 	done
 
+	config_get enb_https "$cfg" enable_https
 	config_get https "$cfg" listen_https
 	config_get UHTTPD_KEY  "$cfg" key  /etc/uhttpd.key
 	config_get UHTTPD_CERT "$cfg" cert /etc/uhttpd.crt
 
-	[ -n "$https" ] && [ "$enb_https" == "1" ] && {
+	[ -f /lib/libustream-ssl.so ] && [ -n "$https" ] && [ -z "$enb_https" -o "$enb_https" == "1" ] && {
 		[ -s "$UHTTPD_CERT" -a -s "$UHTTPD_KEY" ] || {
 			config_foreach generate_keys cert
 		}
@@ -190,7 +211,6 @@ service_triggers()
 }
 
 start_service() {
-	if [ -f /tmp/memoryexpansion ] ; then exit 0; fi
 	config_load uhttpd
 	config_foreach start_instance uhttpd
 }
diff --git a/target/imagebuilder/files/Makefile b/target/imagebuilder/files/Makefile
--- a/target/imagebuilder/files/Makefile
+++ b/target/imagebuilder/files/Makefile
@@ -1,6 +1,6 @@
 # Makefile for OpenWrt
 #
-# Copyright (C) 2007-2010 OpenWrt.org
+# Copyright (C) 2007-2015 OpenWrt.org
 #
 # This is free software, licensed under the GNU General Public License v2.
 # See /LICENSE for more information.
@@ -13,7 +13,7 @@ export TOPDIR LC_ALL LANG
 export OPENWRT_VERBOSE=s
 all: help
 
-include $(TOPDIR)/include/host.mk
+export PATH:=$(TOPDIR)/staging_dir/host/bin:$(PATH)
 
 ifneq ($(OPENWRT_BUILD),1)
   override OPENWRT_BUILD=1
@@ -23,6 +23,7 @@ endif
 include rules.mk
 include $(INCLUDE_DIR)/debug.mk
 include $(INCLUDE_DIR)/depends.mk
+include $(INCLUDE_DIR)/rootfs.mk
 
 include $(INCLUDE_DIR)/version.mk
 export REVISION
@@ -43,6 +44,17 @@ Building images:
 	make image PACKAGES="<pkg1> [<pkg2> [<pkg3> ...]]" # include extra packages
 	make image FILES="<path>" # include extra files from <path>
 	make image BIN_DIR="<path>" # alternative output directory for the images
+	make image EXTRA_IMAGE_NAME="<string>" # Add this to the output image filename (sanitized)
+	make image DISABLED_SERVICES="<svc1> [<svc2> [<svc3> ..]]" # Which services in /etc/init.d/ should be disabled
+	make image ADD_LOCAL_KEY=1 # store locally generated signing key in built images
+
+Print manifest:
+	List "all" packages which get installed into the image.
+	You can use the following parameters:
+
+	make manifest PROFILE="<profilename>" # override the default target profile
+	make manifest PACKAGES="<pkg1> [<pkg2> [<pkg3> ...]]" # include extra packages
+	make manifest STRIP_ABI=1 # remove ABI version from printed package names
 
 endef
 $(eval $(call shexport,Helptext))
@@ -53,124 +65,200 @@ help: FORCE
 
 # override variables from rules.mk
 PACKAGE_DIR:=$(TOPDIR)/packages
-OPKG:= \
-  IPKG_TMP="$(TOPDIR)/tmp/ipkgtmp" \
-  IPKG_INSTROOT="$(TARGET_DIR)" \
-  IPKG_CONF_DIR="$(TOPDIR)/tmp" \
-  IPKG_OFFLINE_ROOT="$(TARGET_DIR)" \
-  $(STAGING_DIR_HOST)/bin/opkg \
+LISTS_DIR:=$(subst $(space),/,$(patsubst %,..,$(subst /,$(space),$(TARGET_DIR))))$(DL_DIR)
+export OPKG_KEYS:=$(TOPDIR)/keys
+OPKG:=$(call opkg,$(TARGET_DIR)) \
 	-f $(TOPDIR)/repositories.conf \
-	--force-depends \
-	--force-overwrite \
-	--force-postinstall \
-	--cache $(TOPDIR)/dl \
-	--offline-root $(TARGET_DIR) \
-	--add-dest root:/ \
-	--add-arch all:100 \
-	--add-arch $(ARCH_PACKAGES):200
-
-define Profile
-  $(eval $(call Profile/Default))
-  $(eval $(call Profile/$(1)))
-  ifeq ($(USER_PROFILE),)
-    USER_PROFILE:=$(1)
-  endif
-  $(1)_NAME:=$(NAME)
-  $(1)_PACKAGES:=$(PACKAGES)
-  PROFILE_LIST += \
-  	echo '$(1):'; [ -z '$(NAME)' ] || echo '	$(NAME)'; echo '	Packages: $(PACKAGES)';
-endef
+	--verify-program $(SCRIPT_DIR)/opkg-key \
+	--cache $(DL_DIR) \
+	--lists-dir $(LISTS_DIR)
 
 include $(INCLUDE_DIR)/target.mk
+-include .profiles.mk
+
+USER_PROFILE ?= $(firstword $(PROFILE_NAMES))
+PROFILE_LIST = $(foreach p,$(PROFILE_NAMES), \
+	echo '$(patsubst DEVICE_%,%,$(p)):'; $(if $($(p)_NAME),echo '    $(subst ','"'"',$($(p)_NAME))'; ) \
+	echo '    Packages: $($(p)_PACKAGES)'; echo '    hasImageMetadata: $($(p)_HAS_IMAGE_METADATA)'; \
+	$(if $($(p)_SUPPORTED_DEVICES),echo '    SupportedDevices: $($(p)_SUPPORTED_DEVICES)';) )
+
+
+.profiles.mk: .targetinfo
+	@$(SCRIPT_DIR)/target-metadata.pl profile_mk $< '$(BOARD)$(if $(SUBTARGET),/$(SUBTARGET))' > $@
+
+staging_dir/host/.prereq-build: include/prereq-build.mk
+	mkdir -p tmp
+	@$(_SINGLE)$(NO_TRACE_MAKE) -j1 -r -s -f $(TOPDIR)/include/prereq-build.mk prereq IB=1 2>/dev/null || { \
+		echo "Prerequisite check failed. Use FORCE=1 to override."; \
+		false; \
+	}
+  ifneq ($(realpath $(TOPDIR)/include/prepare.mk),)
+	@$(_SINGLE)$(NO_TRACE_MAKE) -j1 -r -s -f $(TOPDIR)/include/prepare.mk prepare 2>/dev/null || { \
+		echo "Preparation failed."; \
+		false; \
+	}
+  endif
+	touch $@
 
 _call_info: FORCE
-	echo 'Current Target: "$(BOARD)$(if $(SUBTARGET), ($(BOARDNAME)))"'
+	echo 'Current Target: "$(TARGETID)"'
+	echo 'Current Revision: "$(REVISION)"'
 	echo 'Default Packages: $(DEFAULT_PACKAGES)'
 	echo 'Available Profiles:'
 	echo; $(PROFILE_LIST)
 
-BUILD_PACKAGES:=$(sort $(DEFAULT_PACKAGES) $(USER_PACKAGES) $($(USER_PROFILE)_PACKAGES) kernel)
+BUILD_PACKAGES:=$(USER_PACKAGES) $(sort $(DEFAULT_PACKAGES) $($(USER_PROFILE)_PACKAGES) kernel)
 # "-pkgname" in the package list means remove "pkgname" from the package list
 BUILD_PACKAGES:=$(filter-out $(filter -%,$(BUILD_PACKAGES)) $(patsubst -%,%,$(filter -%,$(BUILD_PACKAGES))),$(BUILD_PACKAGES))
 PACKAGES:=
 
-_call_image:
+_call_image: staging_dir/host/.prereq-build
 	echo 'Building images for $(BOARD)$(if $($(USER_PROFILE)_NAME), - $($(USER_PROFILE)_NAME))'
 	echo 'Packages: $(BUILD_PACKAGES)'
 	echo
+	rm -rf $(TARGET_DIR) $(TARGET_DIR_ORIG)
+	mkdir -p $(TARGET_DIR) $(BIN_DIR) $(TMP_DIR) $(DL_DIR)
+	$(MAKE) package_reload
+	$(MAKE) package_install
+	$(MAKE) -s prepare_rootfs
+	$(MAKE) -s build_image
+	$(MAKE) -s json_overview_image_info
+	$(MAKE) -s checksum
+
+_call_manifest: FORCE
 	rm -rf $(TARGET_DIR)
-	mkdir -p $(TARGET_DIR) $(BIN_DIR) $(TMP_DIR)
-	if [ ! -f "$(PACKAGE_DIR)/Packages" ] || [ ! -f "$(PACKAGE_DIR)/Packages.gz" ] || [ "`find $(PACKAGE_DIR) -cnewer $(PACKAGE_DIR)/Packages.gz`" ]; then \
-		echo "Package list missing or not up-to-date, generating it.";\
+	mkdir -p $(TARGET_DIR) $(BIN_DIR) $(TMP_DIR) $(DL_DIR)
+	$(MAKE) package_reload >/dev/null
+	$(MAKE) package_install >/dev/null
+	$(OPKG) list-installed $(if $(STRIP_ABI),--strip-abi)
+
+package_index: FORCE
+	@echo >&2
+	@echo Building package index... >&2
+	@mkdir -p $(TMP_DIR) $(TARGET_DIR)/tmp
+	(cd $(PACKAGE_DIR); $(SCRIPT_DIR)/ipkg-make-index.sh . > Packages && \
+		gzip -9nc Packages > Packages.gz; \
+		$(if $(CONFIG_SIGNATURE_CHECK), \
+			$(STAGING_DIR_HOST)/bin/usign -S -m Packages -s $(BUILD_KEY)) \
+	) >/dev/null 2>/dev/null
+	$(OPKG) update >&2 || true
+
+package_reload:
+	if [ -d "$(PACKAGE_DIR)" ] && ( \
+			[ ! -f "$(PACKAGE_DIR)/Packages" ] || \
+			[ ! -f "$(PACKAGE_DIR)/Packages.gz" ] || \
+			[ "`find $(PACKAGE_DIR) -cnewer $(PACKAGE_DIR)/Packages.gz`" ] ); then \
+		echo "Package list missing or not up-to-date, generating it." >&2 ;\
 		$(MAKE) package_index; \
 	else \
 		mkdir -p $(TARGET_DIR)/tmp; \
-		$(OPKG) update; \
+		$(OPKG) update >&2 || true; \
 	fi
-	$(MAKE) package_install
-ifneq ($(USER_FILES),)
-	$(MAKE) copy_files
-endif
-	$(MAKE) package_postinst
-	$(MAKE) build_image
 
-package_index: FORCE
-	@echo
-	@echo Building package index...
-	@mkdir -p $(TOPDIR)/tmp $(TOPDIR)/dl $(TARGET_DIR)/tmp
-	(cd $(PACKAGE_DIR); $(SCRIPT_DIR)/ipkg-make-index.sh . > Packages && \
-		gzip -9c Packages > Packages.gz \
-	) >/dev/null 2>/dev/null
-	$(OPKG) update
+package_list: FORCE
+	@$(MAKE) -s package_reload
+	@$(OPKG) list --size 2>/dev/null
 
 package_install: FORCE
 	@echo
 	@echo Installing packages...
-	$(OPKG) install $(PACKAGE_DIR)/libc_*.ipk
-	$(OPKG) install $(PACKAGE_DIR)/kernel_*.ipk
+	$(OPKG) install $(firstword $(wildcard $(LINUX_DIR)/libc_*.ipk $(PACKAGE_DIR)/libc_*.ipk))
+	$(OPKG) install $(firstword $(wildcard $(LINUX_DIR)/kernel_*.ipk $(PACKAGE_DIR)/kernel_*.ipk))
 	$(OPKG) install $(BUILD_PACKAGES)
-	rm -f $(TARGET_DIR)/usr/lib/opkg/lists/*
 
-copy_files: FORCE
+prepare_rootfs: FORCE
 	@echo
-	@echo Copying extra files
-	@$(call file_copy,$(USER_FILES)/*,$(TARGET_DIR)/)
+	@echo Finalizing root filesystem...
 
-package_postinst: FORCE
-	@echo
-	@echo Cleaning up
-	@rm -f $(TARGET_DIR)/tmp/opkg.lock
-	@echo
-	@echo Activating init scripts
-	@( \
-		cd $(TARGET_DIR); \
-		for script in ./etc/init.d/*; do \
-			grep '#!/bin/sh /etc/rc.common' $$script >/dev/null || continue; \
-			IPKG_INSTROOT=$(TARGET_DIR) $(which bash) ./etc/rc.common $$script enable; \
-		done || true; \
+	$(CP) $(TARGET_DIR) $(TARGET_DIR_ORIG)
+	$(if $(CONFIG_SIGNATURE_CHECK), \
+		$(if $(ADD_LOCAL_KEY), \
+			OPKG_KEYS=$(TARGET_DIR)/etc/opkg/keys/ \
+			$(SCRIPT_DIR)/opkg-key add $(BUILD_KEY).pub \
+		) \
 	)
-	$(if $(CONFIG_CLEAN_IPKG),rm -rf $(TARGET_DIR)/usr/lib/opkg)
+	$(call prepare_rootfs,$(TARGET_DIR),$(USER_FILES),$(DISABLED_SERVICES))
 
 build_image: FORCE
 	@echo
 	@echo Building images...
-	$(NO_TRACE_MAKE) -C target/linux/$(BOARD)/image install TARGET_BUILD=1 IB=1 \
+	rm -rf $(BUILD_DIR)/json_info_files/
+	$(NO_TRACE_MAKE) -C target/linux/$(BOARD)/image install TARGET_BUILD=1 IB=1 EXTRA_IMAGE_NAME="$(EXTRA_IMAGE_NAME)" \
 		$(if $(USER_PROFILE),PROFILE="$(USER_PROFILE)")
 
+$(BIN_DIR)/profiles.json: FORCE
+	$(if $(CONFIG_JSON_OVERVIEW_IMAGE_INFO), \
+		WORK_DIR=$(BUILD_DIR)/json_info_files \
+			$(SCRIPT_DIR)/json_overview_image_info.py $@ \
+	)
+
+json_overview_image_info: $(BIN_DIR)/profiles.json
+
+checksum: FORCE
+	@echo
+	@echo Calculating checksums...
+	@$(call sha256sums,$(BIN_DIR))
+
 clean:
-	rm -rf $(TOPDIR)/tmp $(TOPDIR)/dl $(TARGET_DIR) $(BIN_DIR)
+	rm -rf $(TMP_DIR) $(DL_DIR) $(TARGET_DIR) $(BIN_DIR)
 
 
 info:
 	(unset PROFILE FILES PACKAGES MAKEFLAGS; $(MAKE) -s _call_info)
 
+PROFILE_FILTER = $(filter DEVICE_$(PROFILE) $(PROFILE),$(PROFILE_NAMES))
+
+_check_profile: FORCE
+ifneq ($(PROFILE),)
+  ifeq ($(PROFILE_FILTER),)
+	@echo 'Profile "$(PROFILE)" does not exist!'
+	@echo 'Use "make info" to get a list of available profile names.'
+	@exit 1
+  endif
+endif
+
+_check_keys: FORCE
+ifneq ($(CONFIG_SIGNATURE_CHECK),)
+	@if [ ! -s $(BUILD_KEY) -o ! -s $(BUILD_KEY).pub ]; then \
+		echo Generate local signing keys... >&2; \
+		$(STAGING_DIR_HOST)/bin/usign -G \
+			-s $(BUILD_KEY) -p $(BUILD_KEY).pub -c "Local build key"; \
+		$(SCRIPT_DIR)/opkg-key add $(BUILD_KEY).pub; \
+	fi
+	if [ ! -s $(BUILD_KEY).ucert ]; then \
+		echo Generate local certificate... >&2; \
+		$(STAGING_DIR_HOST)/bin/ucert -I \
+			-c $(BUILD_KEY).ucert \
+			-p $(BUILD_KEY).pub \
+			-s $(BUILD_KEY); \
+	fi
+endif
+
 image:
+	$(MAKE) -s _check_profile
+	$(MAKE) -s _check_keys
 	(unset PROFILE FILES PACKAGES MAKEFLAGS; \
-	$(MAKE) _call_image \
-		$(if $(PROFILE),USER_PROFILE="$(PROFILE)") \
+	$(MAKE) -s _call_image \
+		$(if $(PROFILE),USER_PROFILE="$(PROFILE_FILTER)") \
 		$(if $(FILES),USER_FILES="$(FILES)") \
 		$(if $(PACKAGES),USER_PACKAGES="$(PACKAGES)") \
-		$(if $(BIN_DIR),BIN_DIR="$(BIN_DIR)"))
+		$(if $(BIN_DIR),BIN_DIR="$(BIN_DIR)") \
+		$(if $(DISABLED_SERVICES),DISABLED_SERVICES="$(DISABLED_SERVICES)"))
 
-.SILENT: help info image
+manifest: FORCE
+	$(MAKE) -s _check_profile
+	$(MAKE) -s _check_keys
+	(unset PROFILE FILES PACKAGES MAKEFLAGS; \
+	$(MAKE) -s _call_manifest \
+		$(if $(PROFILE),USER_PROFILE="$(PROFILE_FILTER)") \
+		$(if $(PACKAGES),USER_PACKAGES="$(PACKAGES)"))
 
+whatdepends: FORCE
+ifeq ($(PACKAGE),)
+	@echo 'Variable `PACKAGE` is not set but required by `whatdepends`'
+	@exit 1
+endif
+	@$(MAKE) -s package_reload
+	@$(OPKG) whatdepends -A $(PACKAGE)
+
+.SILENT: help info image manifest whatdepends
